/**
 * Angular module settings generated by grunt-angular-settings
 * 
 * (last generated on: `A FEW SECONDS AGO`)
 */

'use strict';

/* jshint quotmark: double */


angular.module("ngSettings", []);



/**
 * example settings block
 */
angular.module("ngSettings").constant("exampleSettings", {
    "foo": "bar",
    "blue": "blah"
});

