/**
 * Angular module settings generated by grunt-angular-settings
 * 
 * (last generated on: `A FEW SECONDS AGO`)
 */

'use strict';

/* jshint quotmark: double */


angular.module("ngSettings", []);



/**
 * extra settings block
 */
angular.module("ngSettings").constant("extraSettings", 12345);

/**
 * extraTwo settings block
 */
angular.module("ngSettings").constant("extraTwoSettings", {
    "foo": "bar",
    "other": [
        1,
        2,
        3,
        4
    ]
});

/**
 * auth settings block
 */
angular.module("ngSettings").constant("authSettings", {
    "sessionTtl": 500,
    "productDataAuthStateRequired": "AuthenticatedVerified",
    "stateLevels": {
        "Unauthenticated": 0,
        "Identified": 1,
        "IdentifiedVerified": 2,
        "Authenticated": 3,
        "AuthenticatedVerified": 4
    },
    "authSessionEvents": {
        "end": {
            "authState": "Unauthenticated",
            "uiState": "login"
        },
        "timeout": {
            "authState": "Identified",
            "uiState": "auth.success"
        }
    }
});

/**
 * productizataion settings block
 */
angular.module("ngSettings").constant("productizataionSettings", {
    "sessionTtl": 700,
    "productDataAuthStateRequired": "AuthenticatedPending",
    "stateLevels": {
        "Unauthenticated": 1234,
        "Identified": 1,
        "IdentifiedVerified": 2,
        "Authenticated": 3,
        "AuthenticatedVerified": 4
    },
    "productizataionSessionEvents": {
        "end": {
            "authState": "Unauthenticated",
            "uiState": "login"
        },
        "timeout": {
            "authState": "Identified",
            "uiState": "product.State"
        }
    }
});

